### ISSUE TITLE
Broken after last update

### ISSUE THREAD

**Issue by toorisrael** [komashchenko/ClientCvarValue#5]
Hi. I believe there's something broken after last CS2 update.

**Comment by komashchenko** [comment]
Hi, try [1.0.6b](https://github.com/komashchenko/ClientCvarValue/releases/tag/v1.0.6b)

**Comment by toorisrael** [comment]
Sadly rebuild doesn't fix the issue
Edit:
It works fine after [those fixes](https://github.com/alliedmodders/hl2sdk/commit/d8dea09acb5e31c311991b52f47dd52eb93808a6)

**Comment by komashchenko** [comment]
Use [1.0.7](https://github.com/komashchenko/ClientCvarValue/releases/tag/v1.0.7)
